bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, Escape, exit,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod SHIFT, V, togglefloating,
bind = $mainMod, F, fullscreen
bind = $mainMod, R, exec, $menu
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle
bind = $mainMod, plus, exec, menu-qalc

# Search window
bind = $mainMod, Tab, exec, rofi -show window

# clipboard manager
bind = $mainMod, V, exec, clipvault list | rofi -dmenu -display-columns 2 | clipvault get | wl-copy

# hyprpicker
bind = $mainMod, h, exec, hyprpicker | wl-copy

# Locking
bind = $mainMod, L, exec, hyprlock

# Screenshot
bind = , Print, exec, grimblast copysave output ~/Screenshots/$(date +'%s_ss.png')
bind = SHIFT, Print, exec, grimblast copysave area ~/Screenshots/$(date +'%s_a_ss.png')
