# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.

# for Img Viewer imv
windowrule = match:class imv, float on

# Steam
windowrule = match:class steam, float on

# for a really bad game
windowrule = match:class BeatEngineTest, float on
windowrule = match:class BeatEngineTest, center on

windowrule = match:class SFML, float on
windowrule = match:class SFML, center on

# osu!
windowrule = match:class osu!.exe , immediate on
