# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# Entire configuration is split between several files inside conf.d.
# You can edit those files or add the configuration in the main
# hyprland.conf. I recommend using the conf.d files.
source=~/.config/hypr/conf.d/keywords.conf
source=~/.config/hypr/conf.d/autostart.conf
source=~/.config/hypr/conf.d/env.conf

source=~/.config/hypr/conf.d/rules/windows.conf
source=~/.config/hypr/conf.d/rules/workspaces.conf

source=~/.config/hypr/conf.d/visuals/animations.conf
source=~/.config/hypr/conf.d/visuals/decoration.conf
source=~/.config/hypr/conf.d/visuals/group.conf
source=~/.config/hypr/conf.d/visuals/cursor.conf
source=~/.config/hypr/conf.d/visuals/misc.conf

source=~/.config/hypr/conf.d/keybinds/keywords.conf
source=~/.config/hypr/conf.d/keybinds/programs.conf
source=~/.config/hypr/conf.d/keybinds/windows.conf
source=~/.config/hypr/conf.d/keybinds/workspaces.conf
source=~/.config/hypr/conf.d/keybinds/special.conf
source=~/.config/hypr/conf.d/keybinds/passthru.conf

source=~/.config/hypr/conf.d/monitors/profile1.conf

#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = latam
    kb_variant =
    kb_model = 
    kb_options =
    kb_rules =
    
    accel_profile = flat
    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
        scroll_factor = 0.2
    }
}

# https://wiki.hypr.land/Configuring/Variables/#gestures
gestures {
}

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
