# See https://wiki.hypr.land/Configuring/Variables/#group

group {
    col.border_active = 0xcc510076
    col.border_inactive = 0xcc29003b
    col.border_locked_active = 0xcc02008d
    col.border_locked_inactive = 0xcc010047
    groupbar {
        font_family = "Iosevka Nerd Font"
        font_size = 10
        height = 15
        indicator_height = 0
        keep_upper_gap = true
        gradients = true
        gaps_in = 0
        gaps_out = 0
        col.active = 0xcc510076
        col.inactive = 0xcc29003b
        col.locked_active = 0xcc02008d
        col.locked_inactive = 0xcc010047
    }
}
