exec-once = waybar & hyprpaper & hypridle & mako
exec-once = mount-onedrive.sh & mount-googledrive.sh
exec-once = wl-paste --watch clipvault store
exec-once = xrandr --output HDMI-A-1 --primary
exec-once = fcitx5 & udiskie
exec-once = hyprpolkitagent

exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
